services:
  - type: web
    name: prowise-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
