export const CATEGORY_ICON_MAP = {
    'electronics': 'hardware-chip-outline',
    'medical device': 'medkit-outline',
    'camera': 'camera-outline',
    'repair skills': 'build-outline',
    'gaming console': 'game-controller-outline',
    'in the home': 'home-outline',
    'appliances': 'tv-outline', 
    'appliance': 'tv-outline',
    'household appliances': 'tv-outline',
    'white goods': 'tv-outline',
    'home appliances': 'tv-outline',
    'mac': 'desktop-outline',
    'macintosh': 'desktop-outline',
    'computer hardware': 'server-outline',
    'pc': 'laptop-outline',
    'laptop': 'laptop-outline',
    'computer': 'laptop-outline',
    'tools': 'hammer-outline',
    'tablet': 'tablet-landscape-outline',
    'ipad': 'tablet-landscape-outline',
    'phone': 'phone-portrait-outline',
    'iphone': 'phone-portrait-outline',
    'samsung': 'hardware-chip-outline', 
    'apple': 'logo-apple',
    'google': 'logo-google',
    'sony': 'logo-playstation',
    'nintendo': 'game-controller-outline',
    'microsoft': 'logo-microsoft',
    'vehicle': 'car-outline',
    'automotive': 'car-outline',
    'apparel & accessories': 'shirt-outline',
    'clothing': 'shirt-outline',
    'car and truck': 'car-sport-outline'
};
